### ISSUE TITLE
Dynamic Animation Replacer not working

### ISSUE THREAD

**Issue by BuschhuepfR** [wabbajack-tools/ussedp#11]
After downgrading, DAR no longer works.

Everything else except DAR works fine.

I have the german version of Skyrim SE AND i read the FAQ on Nexus so i know that it is probably shouldn'd work for non- english version. I just want to know whether it is because of the German version or is it a general problem?

**Comment by halgari** [comment]
It's a problem with their mod then, not with the patcher.
