### ISSUE TITLE
After downpatching, Key inputs do not work at all.

### ISSUE THREAD

**Issue by TuXus3r** [wabbajack-tools/ussedp#12]
After downpatching with the Best Of Both Worlds, My game refuses to take any keyboard inputs, Mouse still works,
Controller works, However last time i played skyrim with Controller was nearly 2 years ago and im not willing to get used to it again, But might do it if i really have no other solutions.
I've tried almost EVERY fix i can think of/is in the internet.
Disabled steam overlay, Check if gamepad is enabled in ini settings, Which it was not.
Add the line bKeyboardEnable=1 under bControllerEnable, Didn't work. Reverifying fixed the issue, But it placed me in the latest version of Skyrim. Fully unmodded/Modded game has the exact same results, SKSE Does absolutely no difference on whether it works or not.
That's about all the fixes i've tried, And none have worked, Please fix, Afaik im the only person with this bug on EARTH. No information about it is in nexus/google about losing keyboard inputs any way or with the Downpatcher.

**Comment by halgari** [comment]
Don't know what to tell you, I just verified my local files. Downloaded the patcher, ran it, started the game, `coc riverwood` key inputs all work fine. Even worked fine to navigate the main menu.
