### ISSUE TITLE
1.6.629 Downgrade 

### ISSUE THREAD

**Issue by matt-laird** [wabbajack-tools/ussedp#37]
**Describe the bug**
Recent version 1.6.629 downgrade does not work.

**To Reproduce**
1. Select your Skyrim exe
2. Click patch
3. Observe error.
> System.Exception: Can't patch file, it doesn't match the expected format
   at Patcher.ViewModels.MainWindowViewModel.PatchFile(Instruction file, AbsolutePath gamePath) in C:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 136
   at Patcher.ViewModels.MainWindowViewModel.Start() in C:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 110
Error! Can't patch file, it doesn't match the expected format
Patching Data\Skyrim - Patch.bsa
File patched
File verified, writing file
Verifying file
Reading Patch File 89ae98da612ab8c8_1595e8bf1a7c957d
Pre-check passed, patching file
Patching binkw64.dll
File already deleted bink2w64.dll
Loaded instructions bestofboth_1.6.353.0_1.5.97.0_2022-01-20
Running instructions
Header matches, loading offsets
Checking for magic header in Z:\home\matt\.var\app\com.valvesoftware.Steam\data\Steam\steamapps\common\Skyrim Special Edition\_\starter-files\BestOfBoth_1.6.353.0-1.5.97.0.exe-57618-2022-01-21-1642729421.exe
Looking for Skyrim Special Edition

**Expected behavior**
Game files to be patched and playable.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version you started from 1.6.629
 - Game Version you downgraded to 1.5.97.0
 - Mod Manager: none

**Additional question**
It would be beneficial to document how we can to produce a new game manifests or such file to allow this tool to function, so that the community can keep the project going, so we can keep playing the game we love.

**Comment by halgari** [comment]
You downloaded the wrong patcher, notice the "from" version in the file you downloaded: BestOfBoth_1.6.353.0-1.5.97.0.exe-57618-2022-01-21-1642729421.exe

**Comment by matt-laird** [comment]
Shheesh... feel a bit silly now. Really appreciate the time for the response.
