### ISSUE TITLE
Raw Patches

### ISSUE THREAD

**Issue by CrezyDud** [wabbajack-tools/ussedp#7]
I can't use dotnet 6.0.0.0 applications on wine right now

can you please give me patch files i can use with any patcher?

**Comment by CrezyDud** [comment]
unless we get it fixed in of #6 course

**Comment by CrezyDud** [comment]
unless we get it fixed in #6 of course

**Comment by KCkingcollin** [comment]
I painstakingly discovered how to compile C# in linux here you go: 
[https://github.com/wabbajack-tools/ussedp/issues/6#issuecomment-979588219](url)

**Comment by KCkingcollin** [comment]
plz close this when you get the chance as ive continued Linux compatibility discussions here... #8 unfortunately the dev can not do anything about winehq's compatibility with dotnet 6.0 so i think it would be more productive to get a compiled version of the app working in linux like i said (https://github.com/wabbajack-tools/ussedp/issues/7#issuecomment-979591122) the app mostly works now its just up to the dev to get a few bugs worked out and we should be off to the races

**Comment by KCkingcollin** [comment]
> I can't use dotnet 6.0.0.0 applications on wine right now
> 
> can you please give me patch files i can use with any patcher?

just realized what you meant by patch files lol my b he just uploaded it on nexus tho... [raw patch files](https://www.nexusmods.com/skyrimspecialedition/mods/57618?tab=files)

**Comment by KCkingcollin** [comment]
btw i just finished getting install scripts ready and tested [here](https://github.com/KCkingcollin/ussedp/tree/patch-1/KCs-Linux-Scripts) if your wanting an easy way to install it...

**Comment by CrezyDud** [comment]
noiz
